### ISSUE TITLE
Script for installasjon

### ISSUE THREAD

**Issue by JohsDevoldMidtun** [ReidarMidtun/PhotoOrganizerScripts#1]
Lage et script for installasjon av "hele pakken". Codeproject AI, .Net 8 framework og applikasjonsfiler.

**Comment by ReidarMidtun** [comment]
Det kan vi gjøre, men jeg foreslår vi venter med dette og prioritere retting av rene feil. 

Issue #2 kan kombineres med denne. Installasjons scriptet vil da foreta en jomfru installasjon eventuelt oppdatere den eksisterende installasjonen.
