### ISSUE TITLE
Rating

### ISSUE THREAD

**Issue by JohsDevoldMidtun** [ReidarMidtun/PhotoOrganizerScripts#3]
Stjernene i rating legges over bildene i Thumbs visning. Er det mulig å legge disse under bildene? Den gule fargen er kanskje heller ikke den beste.

**Comment by ReidarMidtun** [comment]
Ja, det er mulig å legge bildene under thumbnail bildet, men jeg anbefaler det ikke da man må spare så mye skjermplass som mulig. Det vanligste formatet er landskap, i bilder av dette formatet kommer stjernene under selve bildet. Som du ser er også åpne stjerner transparente, dette ble gjort for å kunne se bildet under. Jeg har også prøvd med andre farger som grønn uten at jeg følte at det hjalp.

**Comment by ReidarMidtun** [comment]
![image](https://github.com/ReidarMidtun/PhotoOrganizerScripts/assets/131341486/20767bbc-caeb-4c7c-afba-861278da9ee1)
Har laget en mørk grå bakgrunn, er dette bedre?

**Comment by JohsDevoldMidtun** [comment]
Ja, det ble mye bedre ☺ Johs. Devold MidtunTelefon: 990 35 818Multimidtun as, Kaptein Oppegaards vei 1C, 1164 Oslo  Fra: ReidarMidtun ***@***.***>Dato: fredag, 22. mars 2024 kl. 10:37Til: ReidarMidtun/PhotoOrganizerScripts ***@***.***>Kopi: JohsDevoldMidtun ***@***.***>, Author ***@***.***>Emne: Re: [ReidarMidtun/PhotoOrganizerScripts] Rating (Issue #3)image.png (view on web)Har laget en mørk grå bakgrunn, er dette bedre?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
