### ISSUE TITLE
Remove Source

### ISSUE THREAD

**Issue by JohsDevoldMidtun** [ReidarMidtun/PhotoOrganizerScripts#7]
Fjerner kun bilder fra databasen, men fjerner ikke mappen fra Folders panelet. Den skal vel det?

**Comment by ReidarMidtun** [comment]
Den skal det, det mangler antagelig en refresh, prøv å ta av/på Filter toggle i FolderView.

 

Fra: JohsDevoldMidtun ***@***.***> 
Sendt: mandag 8. april 2024 20:10
Til: ReidarMidtun/PhotoOrganizerScripts ***@***.***>
Kopi: Subscribed ***@***.***>
Emne: [ReidarMidtun/PhotoOrganizerScripts] Remove Source (Issue #7)

 

Fjerner kun bilder fra databasen, men fjerner ikke mappen fra Folders panelet. Den skal vel det?

**Comment by JohsDevoldMidtun** [comment]
Det funket, da forsvant den.
